name: "Chess Game"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Checkout Chess Engine
        uses: actions/checkout@v3
        with:
          repository: 'milaabl/readme-chess'
          path: 'chess-engine'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r chess-engine/requirements.txt

      - name: Execute Move
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          cd chess-engine
          python main.py

      - name: Clean up engine
        run: rm -rf chess-engine

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chess move update"
